# Generated by Django 3.1.2 on 2021-09-30 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210929_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
    ]
