# Generated by Django 3.1.2 on 2020-10-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewEntryText',
        ),
    ]
