# Generated by Django 3.1.2 on 2021-03-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('TY', 'Toy'), ('FS', 'Fashion'), ('ET', 'Electronics'), ('HM', 'Home'), ('TL', 'Tools'), ('AR', 'Art'), ('SP', 'Sports')], max_length=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://st4.depositphotos.com/17828278/24401/v/600/depositphotos_244011872-stock-illustration-image-vector-symbol-missing-available.jpg'),
        ),
    ]
